name: Blog Post Submission
description: Submit a new blog post
title: "[Blog]: "
labels: ["blog"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your blog post!
        感谢您抽时间分享博客文章！

  - type: input
    id: blog-url
    attributes:
      label: Blog URL
      description: The URL of your blog post
      placeholder: https://example.com/your-blog-post
    validations:
      required: true

  - type: textarea
    id: introduction
    attributes:
      label: Brief Introduction & Motivation
      description: |
        Please provide a brief introduction of your blog and why you wrote it
        用一句话或一段话介绍一下写博客初衷和推荐理由
      placeholder: |
        English introduction:
        This blog discusses...

        写作初衷与推荐理由：
        这篇博客主要讨论...
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: Your name or preferred attribution
      placeholder: John Doe
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the primary category for your blog post
      options:
        - Technology
        - Programming
        - Web Development
        - AI/ML
        - Other
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Agreement
      description: By submitting this blog post, you agree to our terms
      options:
        - label: I confirm this is my original content or I have permission to share it
          required: true
        - label: I agree to have this blog post listed in the repository
          required: true 