name: Auto Merge Blog

on:
  issue_comment:
    types: [created]
  issues:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.comment.body == '/approve' && 
       github.event.sender.login == github.repository_owner) ||
      (github.event_name == 'issues' && 
       contains(github.event.issue.labels.*.name, 'approved'))
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Debug Issue Body
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.action }}"
          
      - name: Update README
        run: |
          python .github/scripts/update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Add new blog from issue #${{ github.event.issue.number }}'
          title: 'Add new blog from issue #${{ github.event.issue.number }}'
          body: 'Auto-generated PR from approved issue'
          branch: 'add-blog-${{ github.event.issue.number }}'
          labels: 'auto-merge' 